// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2oHca1dXADB0KU5jcQVe57z_TZ5CpO6U',
    appId: '1:768502731562:web:bc3f1f8e13eef52a34c453',
    messagingSenderId: '768502731562',
    projectId: 'fir-flutter-codelab-2a0f0',
    authDomain: 'fir-flutter-codelab-2a0f0.firebaseapp.com',
    databaseURL:
        'https://fir-flutter-codelab-2a0f0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-2a0f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQjnvvGdCdHxfxnsWtoyyAU8uVYxF3tEM',
    appId: '1:768502731562:android:185c39b4a51e129e34c453',
    messagingSenderId: '768502731562',
    projectId: 'fir-flutter-codelab-2a0f0',
    databaseURL:
        'https://fir-flutter-codelab-2a0f0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-2a0f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTJg7XmmaqIL66DzcShI93RedNceGHTVs',
    appId: '1:768502731562:ios:d0c4d95c3116767e34c453',
    messagingSenderId: '768502731562',
    projectId: 'fir-flutter-codelab-2a0f0',
    databaseURL:
        'https://fir-flutter-codelab-2a0f0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-2a0f0.appspot.com',
    iosClientId:
        '768502731562-b10ge95tgk962luv8puu32i922gn6fr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTJg7XmmaqIL66DzcShI93RedNceGHTVs',
    appId: '1:768502731562:ios:138417f3a1e5841a34c453',
    messagingSenderId: '768502731562',
    projectId: 'fir-flutter-codelab-2a0f0',
    databaseURL:
        'https://fir-flutter-codelab-2a0f0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-2a0f0.appspot.com',
    iosClientId:
        '768502731562-uu5sgij5suddfqfk9rl96mo5u8e9jfpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
